#ifndef CONSTANTS
#define CONSTANTS


#define X_SIZE 100
#define Y_SIZE 50

#define WINDOW_SIZE_X 1900
#define WINDOW_SIZE_Y 1000

#define EMPTY 0


#define PLANKTON 1
#define PLANKTON_COUNT ((X_SIZE * Y_SIZE) / 100) * 30
#define PLANKTON_LIFETIME 30
#define PLANKTON_SPRITE_SCALE 0.019



#define FISH 2
#define FISH_COUNT ((X_SIZE * Y_SIZE) / 100) * 0.3
#define FISH_HUNGER 20
#define FISH_LIFETIME 90
#define FISH_BORN_HUNGER_LIMIT 11
#define MATURE_FISH_AGE 40
#define FISH_VISION_RADIUS 5
#define CHANCE_FISH_BORN_FIVE 20
#define CHANCE_FISH_BORN_THREE 23
#define CHANCE_FISH_BORN_ONE 27
#define FISH_SPRITE_SCALE 0.018
#define FISH1_SPRITE_SCALE 0.08



#define SHARK 3
#define COUNT_SHARKS 7
#define SHARK_HUNGER 70
#define SHARK_BORN_HUNGER_LIMIT 20
#define SHARK_LIFETIME 120
#define SHARK_VISION_RADIUS 40
#define MATURE_SHARK_AGE 70
#define CHANCE_SHARK_BORN_TWINS 20
#define CHANCE_SHARK_BORN_ONE 40
#define SHARK_SPRITE_SCALE 0.095
#define SHARK1_SPRITE_SCALE 0.043

#endif
