#ifndef CONSTANTS
#define CONSTANTS

#define X_SIZE 100
#define Y_SIZE 50

#define WINDOW_SIZE_X 1900
#define WINDOW_SIZE_Y 1000

#define EMPTY 0

#define PLANKTON 1
#define PLANKTON_COUNT ((X_SIZE * Y_SIZE) / 100) * 10
#define PLANKTON_LIFETIME 4
#define PLANKTON_SPRITE_SCALE 0.019

#define FISH 2
#define FISH_COUNT ((X_SIZE * Y_SIZE) / 100) * 2
#define FISH_HUNGER 20
#define FISH_LIFETIME 35
#define FISH_BORN_HUNGER_LIMIT 10
#define MATURE_FISH_AGE 25
#define FISH_VISION_RADIUS 5
#define CHANCE_FISH_BORN_FIVE 10
#define CHANCE_FISH_BORN_THREE 30
#define CHANCE_FISH_BORN_ONE 60
#define FISH_SPRITE_SCALE 0.018
#define FISH1_SPRITE_SCALE 0.08

#define SHARK 3
#define COUNT_SHARKS 10
#define SHARK_HUNGER 40
#define SHARK_BORN_HUNGER_LIMIT 30
#define SHARK_LIFETIME 60
#define SHARK_VISION_RADIUS 20
#define MATURE_SHARK_AGE 45
#define CHANCE_SHARK_BORN_TWINS 20
#define CHANCE_SHARK_BORN_ONE 30
#define SHARK_SPRITE_SCALE 0.095

#endif
