#ifndef CONSTANTS
#define CONSTANTS

#define X_SIZE 100
#define Y_SIZE 50

#define WINDOW_SIZE_X 1900
#define WINDOW_SIZE_Y 1000

#define EMPTY 0

#define PLANKTON 1
#define PLANKTON_COUNT ((X_SIZE * Y_SIZE) / 100) * 10
#define PLANKTON_LIFETIME 8
#define PLANKTON_SPRITE_SCALE 0.019

#define FISH 2
#define FISH_COUNT ((X_SIZE * Y_SIZE) / 100) * 1
#define FISH_HUNGER 17
#define FISH_LIFETIME 25
#define FISH_BORN_HUNGER_LIMIT 14
#define MATURE_FISH_AGE 15
#define FISH_VISION_RADIUS 17
#define CHANCE_FISH_BORN_FIVE 11
#define CHANCE_FISH_BORN_THREE 16
#define CHANCE_FISH_BORN_ONE 32
#define FISH_SPRITE_SCALE 0.018
#define FISH1_SPRITE_SCALE 0.08

#define SHARK 3
#define COUNT_SHARKS 2
#define SHARK_HUNGER 70
#define SHARK_BORN_HUNGER_LIMIT 60
#define SHARK_LIFETIME 120
#define SHARK_VISION_RADIUS 60
#define MATURE_SHARK_AGE 61
#define CHANCE_SHARK_BORN_TWINS -1
#define CHANCE_SHARK_BORN_ONE 0
#define SHARK_SPRITE_SCALE 0.095

#endif
